#**********************************************************************#
#                                                                      #
#                        FoCaLize compiler                             #
#                                                                      #
#            François Pessaux                                          #
#            Pierre Weis                                               #
#            Damien Doligez                                            #
#                                                                      #
#                               LIP6  --  INRIA Rocquencourt           #
#                                                                      #
#  Copyright 2008 LIP6 and INRIA                                       #
#  Distributed only by permission.                                     #
#                                                                      #
#**********************************************************************#

# $Id: Makefile.config,v 1.1 2008-11-30 21:47:14 weis Exp $

# The list of tar balls for external tools that are MANDATORY for focalize to
# work properly.

# The first step of the installation process is to untar, compile and install
# all those tools.
EXTERNAL_TOOLS_TAR_BALLS = camlp5-5.09.tgz  coq-8.1pl4.tar.gz ocaml-3.10.2.tar.gz
EXTERNAL_TOOLS_DIR = camlp5-5.09  coq-8.1pl4 ocaml-3.10.2
