#**********************************************************************#
#                                                                      #
#                        FoCaLize compiler                             #
#                                                                      #
#            François Pessaux                                          #
#            Pierre Weis                                               #
#            Damien Doligez                                            #
#                                                                      #
#                               LIP6  --  INRIA Rocquencourt           #
#                                                                      #
#  Copyright 2008 LIP6 and INRIA                                       #
#  Distributed only by permission.                                     #
#                                                                      #
#**********************************************************************#

# $Id: Makefile.config,v 1.7 2008-12-03 20:55:33 weis Exp $

# General commands
CD = cd
LN = ln -sf
CP = cp
MKDIR = mkdir -p
TARX = tar xvzf

# Software configuration variables.
include $(ROOT_DIR)/.config_var

#
## MANAGING EXTERNAL TOOLS ##
#

# Focalize distribution includes the external tools that are MANDATORY for
# focalize to work properly.
# We must provide almost all their transitive closure :(
# The first step of the installation process is to untar, compile and install
# all those tools.

# The directory where the tar balls are stored.
TAR_BALLS_DIR_NAME = tarballs
TAR_BALLS_DIR = $(ROOT_DIR)/$(TAR_BALLS_DIR_NAME)
ABSOLUTE_TAR_BALLS_DIR = $(ABSOLUTE_ROOT_DIR)/$(TAR_BALLS_DIR_NAME)

# For each tool, we define its sub-directory, its tar ball file name,
# its configuration options, and make all target.

# The Caml compiler
CAML_DIR_NAME = ocaml-3.10.2
CAML_EXE_NAME = ocamlc
CAML_DIR = $(ROOT_DIR)/$(CAML_DIR_NAME)
ABSOLUTE_CAML_DIR = $(ABSOLUTE_ROOT_DIR)/$(CAML_DIR_NAME)
CAML_EXE = $(ABSOLUTE_CAML_DIR)/$(CAML_EXE_NAME)

CAML_TAR_BALL = $(CAML_DIR_NAME).tar.gz
CAML_CONFIGURE_OPTIONS = -prefix $(PREFIX)
CAML_MAKE_ALL_TARGET = world.opt

# The Caml pre-processor
CAMLP5_DIR_NAME = camlp5-5.09
CAMLP5_EXE_NAME = camlp5
CAMLP5_DIR = $(ROOT_DIR)/$(CAMLP5_DIR_NAME)
ABSOLUTE_CAMLP5_DIR = $(ABSOLUTE_ROOT_DIR)/$(CAMLP5_DIR_NAME)
CAMLP5_EXE = $(ABSOLUTE_CAMLP5_DIR)/$(CAMLP5_EXE_NAME)

CAMLP5_TAR_BALL = $(CAMLP5_DIR_NAME).tgz
CAMLP5_CONFIGURE_OPTIONS = -transitional -prefix $(PREFIX)
CAMLP5_MAKE_ALL_TARGET = world.opt

# The Coq proof assistant
COQ_DIR_NAME = coq-8.1pl4
COQ_EXE_NAME = coqc
COQ_DIR = $(ROOT_DIR)/$(COQ_DIR_NAME)
ABSOLUTE_COQ_DIR = $(ABSOLUTE_ROOT_DIR)/$(COQ_DIR_NAME)
COQ_EXE = $(ABSOLUTE_COQ_DIR)/$(COQ_EXE_NAME)

COQ_TAR_BALL = $(COQ_DIR_NAME).tar.gz
COQ_CONFIGURE_OPTIONS = -prefix $(PREFIX) -camldir $(ABSOLUTE_CAML_DIR) \
-camlp5dir $(ABSOLUTE_ROOT_DIR)/$(CAMLP5_DIR)
COQ_MAKE_ALL_TARGET = world.opt

# Convenient abbrevs for all external tools stuff.
EXTERNAL_TOOLS_TAR_BALLS = $(CAML_TAR_BALL) $(CAMLP5_TAR_BALL) $(COQ_TAR_BALL)
EXTERNAL_TOOLS_DIRS = $(ROOT_DIR)/$(CAML_DIR) $(ROOT_DIR)/$(CAMLP5_DIR) $(ROOT_DIR)/$(COQ_DIR)
EXTERNAL_TOOLS_EXES = $(CAML_EXE) $(CAMLP5_EXE) $(COQ_EXE)

#
## MANAGING INTERNAL TOOLS ##
#

# Internal tools are zenon (the automatic proof generator), zvtov (the
# translator from zenon proofs to coq proof lambda-terms), and focalizec (the
# compiler for focalize programs).
# All these tools are compiled in turn after configuration.

ZENON_DIR_NAME = zenon
ZENON_EXE_NAME = zenon
ZENON_DIR = $(ROOT_DIR)/$(ZENON_DIR_NAME)
ABSOLUTE_ZENON_DIR =
ZENON_EXE = $(ABSOLUTE_ZENON_DIR)/$(ZENON_EXE_NAME)

ZVTOV_DIR_NAME = zvtov
ZVTOV_EXE_NAME = zvtov
ZVTOV_DIR = $(ROOT_DIR)/$(ZVTOV_DIR_NAME)
ABSOLUTE_ZVTOV_DIR = $(ABSOLUTE_ROOT_DIR)/$(ZVTOV_DIR_NAME)
ZVTOV_EXE = $(ABSOLUTE_ZVTOV_DIR)/$(ZVTOV_EXE_NAME)

FOCALIZEC_DIR_NAME = focalizec
FOCALIZEC_EXE_NAME = focalizec
FOCALIZEC_DIR = $(ROOT_DIR)/$(FOCALIZEC_DIR_NAME)
ABSOLUTE_FOCALIZEC_DIR = $(ABSOLUTE_ROOT_DIR)/$(FOCALIZEC_DIR_NAME)
FOCALIZEC_EXE = $(ABSOLUTE_FOCALIZEC_DIR)/$(FOCALIZEC_EXE_NAME)

INTERNAL_TOOLS_DIRS = $(ZENON_DIR) $(ZVTOV_DIR) $(FOCALIZEC_DIR)
INTERNAL_TOOLS_EXES = $(ZENON_EXE) $(ZVTOV_EXE) $(FOCALIZEC_EXE)
