# General utilities and commands. Excludes OCaml and Coq.
include $(ROOT_DIR)/Makefile.utils

# Implicit rules.
include $(ROOT_DIR)/Makefile.rules

# Compilers: OCaml and Coq
include $(ROOT_DIR)/.config_var
