
help:
	@echo 'usage: make [all | clean | cleanall | cleanxml | help ]'

all clean cleanall cleanxml:
	make -f Makefile.D $@
#	make -f Makefile.pair_modulo $@
#	make -f Makefile.modulo $@
#	for makefile in Makefile.*; do make -f $$makefile $@; done

