RM = rm -rf
CD = cd

CAMLBYT = ocamlc -w A -warn-error Ae -g
CAMLBIN = ocamlopt -w A -warn-error Ae
CAMLDOC = ocamldoc
CAMLYACC = ocamlyacc -v
CAMLLEX = ocamllex
CAMLDEP = ocamldep

COQC = coqc

MAKE = make
