# $Id: Makefile.config,v 1.7 2008-09-24 07:14:34 weis Exp $

# Basic Unix commands
MAKE = make
RM = rm -rf
CD = cd
LN = ln -sf

# The compilers

# Caml compiler
CAML_COMP_FLAGS =
CAMLBYT = ocamlc -g -w A -warn-error Ae $(CAML_COMP_FLAGS)
CAMLBIN = ocamlopt -w A -warn-error Ae $(CAML_COMP_FLAGS)
CAMLDOC = ocamldoc
CAMLYACC = ocamlyacc -v
CAMLLEX = ocamllex
CAMLDEP = ocamldep $(CAML_COMP_FLAGS)

# Focalize compiler
FOCAL_COMP_FLAGS =
FOCAL_COMPILER = focalizec
FOCALC = $(FOCAL_COMPILER) $(FOCAL_COMP_FLAGS)

# Coq compiler
COQ_COMP_FLAGS =
COQ_COMPILER = coqc
COQC = $(COQ_COMPILER) $(COQ_COMP_FLAGS)

ZVTOV= zvtov
