#**********************************************************************#
#                                                                      #
#                        FoCaLize compiler                             #
#                                                                      #
#            François Pessaux                                          #
#            Pierre Weis                                               #
#            Damien Doligez                                            #
#                               LIP6  --  INRIA Rocquencourt           #
#                                                                      #
#  Copyright 2008 LIP6 and INRIA                                       #
#  Distributed only by permission.                                     #
#                                                                      #
#**********************************************************************#

# $Id: Makefile.config,v 1.22 2008-11-25 06:47:17 weis Exp $

# Basic Unix commands
MAKE = make
RM = rm -rf
CD = cd
LN = ln -sf
CP = cp
MKDIR = mkdir -p

# The compilers

# Tex related processors
LATEX = latex
MAKEINDEX = makeindex
DVIPS = dvips
DVIPDF = dvipdf

# Caml compiler commands
CAML_BYT_COMPILER = ocamlc
CAML_BIN_COMPILER = ocamlopt

# Caml compilers flags
CAML_COMP_FLAGS = -w A -warn-error Ae -dtypes
CAML_BYT_COMP_FLAGS = $(CAML_COMP_FLAGS) -g
CAML_BIN_COMP_FLAGS = $(CAML_COMP_FLAGS)

# Caml libraries includes for compilation, linking, and dependancy computation.
CAML_INCLUDES =

# The Caml byte and bin compiler definitions.
CAML_BYT = $(CAML_BYT_COMPILER) $(CAML_INCLUDES) $(CAML_BYT_COMP_FLAGS)
CAML_BIN = $(CAML_BIN_COMPILER) $(CAML_INCLUDES) $(CAML_BIN_COMP_FLAGS)

# Other Caml related commands
CAML_DOC = ocamldoc
CAML_YACC = ocamlyacc -v
CAML_LEX = ocamllex
CAML_DEP = ocamldep $(CAML_INCLUDES)

# The focalize compiler command
LINK_TO_FOCALIZE_COMPILER = $(ROOT_DIR)/toplevel/focalizec
# The byt compiled focalize compiler
BYT_FOCALIZE_COMPILER = $(LINK_TO_FOCALIZE_COMPILER).byt
# The binary compiled focalize compiler
BIN_FOCALIZE_COMPILER = $(BYT_FOCALIZE_COMPILER:.byt=.bin)
# The regular focalize compiler command
FOCALIZE_COMPILER = $(LINK_TO_FOCALIZE_COMPILER)

# The focalize compiler flags
FOCALIZE_COMP_FLAGS =

# The focalize compiler definition
FOCALIZEC = $(FOCALIZE_COMPILER) $(FOCALIZE_COMP_FLAGS)

# The Coq compiler command
COQ_COMPILER = coqc

# The Coq compiler flags
COQ_COMP_FLAGS =

# The Coq libraries includes for compilation.
COQ_INCLUDES = -I $(ROOT_DIR)/../zenon/

# The Coq compiler definition
COQC = $(COQ_COMPILER) $(COQ_INCLUDES) $(COQ_COMP_FLAGS)

# The Zenon compiler command
ZENON_COMPILER = $(ROOT_DIR)/../zenon/zenon
# The Zenon compiler flags
ZENON_COMP_FLAGS = -max-time 5m

# The zenon compiler definition. (Only for completeness).
# Note: we do not directly use $(ZENON) in focalize: we use $(ZVTOV) instead,
# with options to call zenon with the appropriate options.
ZENON = $(ZENON_COMPILER) $(ZENON_COMP_FLAGS)

# The Zvtov compiler
ZVTOV_COMPILER = $(ROOT_DIR)/../zvtov/zvtov

# The Zvtov compiler flags
ZVTOV_COMP_FLAGS = -zz "$(ZENON_COMP_FLAGS)" -zenon $(ZENON_COMPILER) -new

# The Zvtov compiler definition
ZVTOV = $(ZVTOV_COMPILER) $(ZVTOV_COMP_FLAGS)
