(***********************************************************************)
(*                                                                     *)
(*                        FoCaL compiler                               *)
(*            François Pessaux                                         *)
(*            Pierre Weis                                              *)
(*            Damien Doligez                                           *)
(*                               LIP6  --  INRIA Rocquencourt          *)
(*                                                                     *)
(*  Copyright 2007 LIP6 and INRIA                                      *)
(*  Distributed only by permission.                                    *)
(*                                                                     *)
(***********************************************************************)

(* $Id: externals_generation_errs.mli,v 1.1 2008-04-09 10:19:44 pessaux Exp $ *)


exception No_external_value_def of (string * Parsetree.vname * Location.t)
exception No_external_type_def of (string * Parsetree.vname * Location.t)
exception No_external_constructor_def of (string * Parsetree.constructor_ident)
exception No_external_field_def of (string * Parsetree.label_ident)
