# $Id: Makefile,v 1.10 2008-09-18 22:39:00 weis Exp $

ROOTDIR = ..

include $(ROOTDIR)/Makefile.config

CAML_COMP_FLAGS = -I ../basement -I ../parser -I ../typing

BYTOBJS = visUniverse.cmo minEnv.cmo abstractions.cmo misc_common.cmo\
	externals_generation_errs.cmo recursion.cmo

include $(ROOTDIR)/Makefile.common
