all:
	@make -f Makefile_triangle all
	@make -f Makefile_length all

clean:
	@make -f Makefile_triangle clean
	@make -f Makefile_length clean

cleanall:
	@make -f Makefile_triangle cleanall
	@make -f Makefile_length cleanall

cleanxml:
	@make -f Makefile_triangle cleanxml
	@make -f Makefile_length cleanxml

.DEFAULT_GOAL := all
.PHONY: all clean cleanall cleanxml
