SPECIES="couple\#Groupe_couple_list_int"
LIBRARY=couple
FOCTEST_OPTS=
PROPERTIES= 'plus_is_monotone, thm_plus_convert'
NUMBER_OF_TEST=100
SIZE_OF_ELEM=10
XMLFILE=couple_list_int.xml

CMO_TO_LINK = ml_builtins.cmo sets_externals.cmo basics.cmo  sets.cmo

OCAML_OBJ= unix.cma
XSLTPATH=../xml

include ../Makefile.test
