SPECIES='small_naturals'
LIBRARY=small_integers
FOCTEST_OPTS=
PROPERTIES='even_odd_complete, one_is_odd, order_inf_is_transitive, \
					  geq_transitive, geq_absorbes_add, leq_absorbes_add, \
						order_compatible_with_cancellation, order_compatible_with_plus, \
						total_order, leq_transitive, successor_of_even_is_odd, \
						successor_of_odd_is_even, mult2_produces_even, zero_is_even, \
						inf_absorbes_add, leq_refines_order_inf, order_sup_refines_order_inf, \
						order_inf_refines_order_sup, order_sup_is_supremum, \
						order_sup_is_transitive, sup_absorbes_add, geq_refines_order_sup, \
						order_inf_is_infimum'
NUMBER_OF_TEST=100
SIZE_OF_ELEM=1073741823
XMLFILE=test_report.xml
REINJECT=reinject.xml
CMO_TO_LINK= caml_basics.cmo openmath.cmo basics0.cmo sets_orders.cmo \
						 iterators.cmo multiplicative_law.cmo additive_law.cmo \
						 random_foc.cmo weak_structures.cmo rings_fields.cmo \
						 integers.cmo

OCAML_OBJ= unix.cma
XSLTPATH=../xml

#include ../Makefile.test
